# Single vagrant config file for test purposes:
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.network "forwarded_port", guest: 9200, host: 9200
  config.vm.network "forwarded_port", guest: 8070, host: 8070

  # config.vm.synced_folder "~/tests", "/opt/tests"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "4096"
  end

 config.vm.provision "shell", inline: <<-SHELL
     apt-get install -y git ncdu htop wget mc unzip &&
     su vagrant -c "cd && mkdir tests && cd tests && wget -c https://raw.githubusercontent.com/softctrl/twitter-stats/master/projects/shell/setup_env.sh && chmod +x setup_env.sh && ./setup_env.sh"
 SHELL

end
